steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/lariballs/image1', '.']
  dir: 'webbi'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/lariballs/image2', '.']
  env: ['PROJECT_ROOT=lariballs']
  dir: 'db'
images: ['gcr.io/lariballs/image1', 'gcr.io/lariballs/image2']
