steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t', 'gcr.io/my-project/image1', '.']
  env: ['PROJECT_ROOT=lariballs']
  dir: 'webbi'

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/my-project/image2''.']
  env: ['PROJECT_ROOT=lariballs']
  dir: 'db'
images: ['gcr.io/my-project/image1', 'gcr.io/my-project/image2']
