steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/lariballs/image1', '.']
  dir: 'webbi'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/lariballs/image2', '.']
  env: ['PROJECT_ROOT=lariballs']
  dir: 'db'
#ei tartte images: ['gcr.io/lariballs/image1', 'gcr.io/lariballs/image2']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/lariballs/image1']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/lariballs/image2']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'tballs', '--image', 'gcr.io/lariballs/image2', '--region', 'us-central1', '--platform', 'managed', '--quiet']
images:
       - gcr.io/lariballs/image2
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'tballs', '--image', 'gcr.io/lariballs/image1', '--region', 'us-central1', '--platform', 'managed', '--quiet]
images:
       - gcr.io/lariballs/image1




